# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestCadastro():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastro(self):
    # Test name: Cadastro
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://www.idealplacas.com/")
    # 2 | setWindowSize | 1095x630 |  | 
    self.driver.set_window_size(1095, 630)
    # 3 | click | css=.fa-user |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-user").click()
    # 4 | click | css=form:nth-child(1) > .button |  | 
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(1) > .button").click()
    # 5 | click | id=nomerazao |  | 
    self.driver.find_element(By.ID, "nomerazao").click()
    # 6 | type | id=nomerazao | Emerson Pinheiro de Souza | 
    self.driver.find_element(By.ID, "nomerazao").send_keys("Emerson Pinheiro de Souza")
    # 7 | click | id=genero |  | 
    self.driver.find_element(By.ID, "genero").click()
    # 8 | select | id=genero | label=Masculino | 
    dropdown = self.driver.find_element(By.ID, "genero")
    dropdown.find_element(By.XPATH, "//option[. = 'Masculino']").click()
    # 9 | click | id=genero |  | 
    self.driver.find_element(By.ID, "genero").click()
    # 10 | click | id=nascimento |  | 
    self.driver.find_element(By.ID, "nascimento").click()
    # 11 | type | id=nascimento | 07/01/1982 | 
    self.driver.find_element(By.ID, "nascimento").send_keys("07/01/1982")
    # 12 | type | id=documento | 852.585.982-68 | 
    self.driver.find_element(By.ID, "documento").send_keys("852.585.982-68")
    # 13 | type | id=ddd | 92 | 
    self.driver.find_element(By.ID, "ddd").send_keys("92")
    # 14 | type | id=fixocomercial | 9810-3663 | 
    self.driver.find_element(By.ID, "fixocomercial").send_keys("9810-3663")
    # 15 | type | id=celular | 9810-3663 | 
    self.driver.find_element(By.ID, "celular").send_keys("9810-3663")
    # 16 | type | id=cep | 69.028-347 | 
    self.driver.find_element(By.ID, "cep").send_keys("69.028-347")
    # 17 | select | id=estado | label=São Paulo | 
    dropdown = self.driver.find_element(By.ID, "estado")
    dropdown.find_element(By.XPATH, "//option[. = 'São Paulo']").click()
    # 18 | select | id=estado | label=Rio de Janeiro | 
    dropdown = self.driver.find_element(By.ID, "estado")
    dropdown.find_element(By.XPATH, "//option[. = 'Rio de Janeiro']").click()
    # 19 | select | id=estado | label=Minhas Gerais | 
    dropdown = self.driver.find_element(By.ID, "estado")
    dropdown.find_element(By.XPATH, "//option[. = 'Minhas Gerais']").click()
    # 20 | select | id=estado | label=Bahia | 
    dropdown = self.driver.find_element(By.ID, "estado")
    dropdown.find_element(By.XPATH, "//option[. = 'Bahia']").click()
    # 21 | select | id=estado | label=Rio Grande do Sul | 
    dropdown = self.driver.find_element(By.ID, "estado")
    dropdown.find_element(By.XPATH, "//option[. = 'Rio Grande do Sul']").click()
    # 22 | select | id=estado | label=Amazonas | 
    dropdown = self.driver.find_element(By.ID, "estado")
    dropdown.find_element(By.XPATH, "//option[. = 'Amazonas']").click()
    # 23 | type | id=cidade | Manaus | 
    self.driver.find_element(By.ID, "cidade").send_keys("Manaus")
    # 24 | type | id=bairro | Flores | 
    self.driver.find_element(By.ID, "bairro").send_keys("Flores")
    # 25 | type | id=endereco | Rua 1 | 
    self.driver.find_element(By.ID, "endereco").send_keys("Rua 1")
    # 26 | type | id=numero | 20 | 
    self.driver.find_element(By.ID, "numero").send_keys("20")
    # 27 | type | id=complemento | Sta Cruz | 
    self.driver.find_element(By.ID, "complemento").send_keys("Sta Cruz")
    # 28 | type | id=observacoes | Nenhuma | 
    self.driver.find_element(By.ID, "observacoes").send_keys("Nenhuma")
    # 29 | type | id=email | emerson@bol.com | 
    self.driver.find_element(By.ID, "email").send_keys("emerson@bol.com")
    # 30 | type | id=senha | overid123 | 
    self.driver.find_element(By.ID, "senha").send_keys("overid123")
    # 31 | type | id=rSenha | overid123 | 
    self.driver.find_element(By.ID, "rSenha").send_keys("overid123")
    # 32 | click | css=.button:nth-child(22) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".button:nth-child(22)").click()
  
