# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestCadSelect():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadSelect(self):
    # Test name: CadSelect
    # Step # | name | target | value | comment
    # 1 | open | /cad-cliente |  | 
    self.driver.get("http://www.idealplacas.com/cad-cliente")
    # 2 | setWindowSize | 1095x630 |  | 
    self.driver.set_window_size(1095, 630)
    # 3 | click | css=label:nth-child(2) > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(2) > input").click()
    # 4 | click | name=doc |  | 
    self.driver.find_element(By.NAME, "doc").click()
    # 5 | click | css=label:nth-child(2) > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(2) > input").click()
    # 6 | click | name=doc |  | 
    self.driver.find_element(By.NAME, "doc").click()
  
